# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entrance_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entrance_form(object):
    def setupUi(self, entrance_form):
        entrance_form.setObjectName("entrance_form")
        entrance_form.resize(206, 310)
        self.verticalLayout = QtWidgets.QVBoxLayout(entrance_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(entrance_form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.entrance_page = QtWidgets.QWidget()
        self.entrance_page.setObjectName("entrance_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.entrance_page)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.entrance_label = QtWidgets.QLabel(self.entrance_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrance_label.sizePolicy().hasHeightForWidth())
        self.entrance_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entrance_label.setFont(font)
        self.entrance_label.setAlignment(QtCore.Qt.AlignCenter)
        self.entrance_label.setObjectName("entrance_label")
        self.verticalLayout_2.addWidget(self.entrance_label)
        self.entrance_login = QtWidgets.QLineEdit(self.entrance_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrance_login.sizePolicy().hasHeightForWidth())
        self.entrance_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.entrance_login.setFont(font)
        self.entrance_login.setObjectName("entrance_login")
        self.verticalLayout_2.addWidget(self.entrance_login)
        self.entrance_password = QtWidgets.QLineEdit(self.entrance_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrance_password.sizePolicy().hasHeightForWidth())
        self.entrance_password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.entrance_password.setFont(font)
        self.entrance_password.setObjectName("entrance_password")
        self.verticalLayout_2.addWidget(self.entrance_password)
        self.entrance_button_enter = QtWidgets.QPushButton(self.entrance_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrance_button_enter.sizePolicy().hasHeightForWidth())
        self.entrance_button_enter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.entrance_button_enter.setFont(font)
        self.entrance_button_enter.setObjectName("entrance_button_enter")
        self.verticalLayout_2.addWidget(self.entrance_button_enter)
        self.entrance_button_register = QtWidgets.QPushButton(self.entrance_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrance_button_register.sizePolicy().hasHeightForWidth())
        self.entrance_button_register.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.entrance_button_register.setFont(font)
        self.entrance_button_register.setObjectName("entrance_button_register")
        self.verticalLayout_2.addWidget(self.entrance_button_register)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.stackedWidget.addWidget(self.entrance_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.register_page)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.register_label = QtWidgets.QLabel(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_label.sizePolicy().hasHeightForWidth())
        self.register_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.register_label.setFont(font)
        self.register_label.setAlignment(QtCore.Qt.AlignCenter)
        self.register_label.setObjectName("register_label")
        self.verticalLayout_3.addWidget(self.register_label)
        self.register_personal_name = QtWidgets.QLineEdit(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_personal_name.sizePolicy().hasHeightForWidth())
        self.register_personal_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_personal_name.setFont(font)
        self.register_personal_name.setObjectName("register_personal_name")
        self.verticalLayout_3.addWidget(self.register_personal_name)
        self.register_login = QtWidgets.QLineEdit(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_login.sizePolicy().hasHeightForWidth())
        self.register_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_login.setFont(font)
        self.register_login.setObjectName("register_login")
        self.verticalLayout_3.addWidget(self.register_login)
        self.register_password_1 = QtWidgets.QLineEdit(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_password_1.sizePolicy().hasHeightForWidth())
        self.register_password_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_password_1.setFont(font)
        self.register_password_1.setObjectName("register_password_1")
        self.verticalLayout_3.addWidget(self.register_password_1)
        self.register_password_2 = QtWidgets.QLineEdit(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_password_2.sizePolicy().hasHeightForWidth())
        self.register_password_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_password_2.setFont(font)
        self.register_password_2.setObjectName("register_password_2")
        self.verticalLayout_3.addWidget(self.register_password_2)
        self.register_button_register = QtWidgets.QPushButton(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_button_register.sizePolicy().hasHeightForWidth())
        self.register_button_register.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_button_register.setFont(font)
        self.register_button_register.setObjectName("register_button_register")
        self.verticalLayout_3.addWidget(self.register_button_register)
        self.stackedWidget.addWidget(self.register_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_task_list = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_task_list.setFont(font)
        self.label_task_list.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_list.setObjectName("label_task_list")
        self.verticalLayout_4.addWidget(self.label_task_list)
        self.task_list = QtWidgets.QListWidget(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task_list.setFont(font)
        self.task_list.setObjectName("task_list")
        self.verticalLayout_4.addWidget(self.task_list)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(entrance_form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(entrance_form)

    def retranslateUi(self, entrance_form):
        _translate = QtCore.QCoreApplication.translate
        entrance_form.setWindowTitle(_translate("entrance_form", "Dialog"))
        self.entrance_label.setText(_translate("entrance_form", "Вход"))
        self.entrance_login.setPlaceholderText(_translate("entrance_form", "Логин"))
        self.entrance_password.setPlaceholderText(_translate("entrance_form", "Пароль"))
        self.entrance_button_enter.setText(_translate("entrance_form", "Вход"))
        self.entrance_button_register.setText(_translate("entrance_form", "Регистрация"))
        self.register_label.setText(_translate("entrance_form", "Студент"))
        self.register_personal_name.setPlaceholderText(_translate("entrance_form", "ФИО"))
        self.register_login.setPlaceholderText(_translate("entrance_form", "Логин"))
        self.register_password_1.setPlaceholderText(_translate("entrance_form", "Пароль"))
        self.register_password_2.setPlaceholderText(_translate("entrance_form", "Повторите пароль"))
        self.register_button_register.setText(_translate("entrance_form", "Регистрация"))
        self.label_task_list.setText(_translate("entrance_form", "Доступные задания"))
