# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checking_answers_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_answers_window(object):
    def setupUi(self, check_answers_window):
        check_answers_window.setObjectName("check_answers_window")
        check_answers_window.resize(780, 534)
        self.horizontalLayout = QtWidgets.QHBoxLayout(check_answers_window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_of_tasks = QtWidgets.QListWidget(check_answers_window)
        self.list_of_tasks.setObjectName("list_of_tasks")
        self.verticalLayout.addWidget(self.list_of_tasks)
        self.list_of_students = QtWidgets.QListWidget(check_answers_window)
        self.list_of_students.setObjectName("list_of_students")
        self.verticalLayout.addWidget(self.list_of_students)
        self.list_of_answers = QtWidgets.QListWidget(check_answers_window)
        self.list_of_answers.setObjectName("list_of_answers")
        self.verticalLayout.addWidget(self.list_of_answers)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_total_figs_task = QtWidgets.QLabel(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_total_figs_task.setFont(font)
        self.label_total_figs_task.setObjectName("label_total_figs_task")
        self.verticalLayout_3.addWidget(self.label_total_figs_task)
        self.label_total_figs_answer = QtWidgets.QLabel(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_total_figs_answer.setFont(font)
        self.label_total_figs_answer.setObjectName("label_total_figs_answer")
        self.verticalLayout_3.addWidget(self.label_total_figs_answer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.button_show_task_text = QtWidgets.QPushButton(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_show_task_text.setFont(font)
        self.button_show_task_text.setObjectName("button_show_task_text")
        self.horizontalLayout_2.addWidget(self.button_show_task_text)
        self.button_show_answer_text = QtWidgets.QPushButton(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_show_answer_text.setFont(font)
        self.button_show_answer_text.setObjectName("button_show_answer_text")
        self.horizontalLayout_2.addWidget(self.button_show_answer_text)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_found_correct = QtWidgets.QLabel(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_found_correct.setFont(font)
        self.label_found_correct.setObjectName("label_found_correct")
        self.verticalLayout_2.addWidget(self.label_found_correct)
        self.text_found_correct = QtWidgets.QTextBrowser(check_answers_window)
        self.text_found_correct.setObjectName("text_found_correct")
        self.verticalLayout_2.addWidget(self.text_found_correct)
        self.label_found_wrong = QtWidgets.QLabel(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_found_wrong.setFont(font)
        self.label_found_wrong.setObjectName("label_found_wrong")
        self.verticalLayout_2.addWidget(self.label_found_wrong)
        self.text_found_wrong = QtWidgets.QTextBrowser(check_answers_window)
        self.text_found_wrong.setObjectName("text_found_wrong")
        self.verticalLayout_2.addWidget(self.text_found_wrong)
        self.label_not_found = QtWidgets.QLabel(check_answers_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_not_found.setFont(font)
        self.label_not_found.setObjectName("label_not_found")
        self.verticalLayout_2.addWidget(self.label_not_found)
        self.text_not_found = QtWidgets.QTextBrowser(check_answers_window)
        self.text_not_found.setObjectName("text_not_found")
        self.verticalLayout_2.addWidget(self.text_not_found)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)

        self.retranslateUi(check_answers_window)
        QtCore.QMetaObject.connectSlotsByName(check_answers_window)

    def retranslateUi(self, check_answers_window):
        _translate = QtCore.QCoreApplication.translate
        check_answers_window.setWindowTitle(_translate("check_answers_window", "Проверка заданий"))
        self.label_total_figs_task.setText(_translate("check_answers_window", "Всего оборотов в задании"))
        self.label_total_figs_answer.setText(_translate("check_answers_window", "Всего оборотов в ответе"))
        self.button_show_task_text.setText(_translate("check_answers_window", "Текст задания"))
        self.button_show_answer_text.setText(_translate("check_answers_window", "Текст ответа"))
        self.label_found_correct.setText(_translate("check_answers_window", "Найдено правильно"))
        self.label_found_wrong.setText(_translate("check_answers_window", "Найдено неправильно"))
        self.label_not_found.setText(_translate("check_answers_window", "Не найдено"))
