# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entrance_form_teacher.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entrance_form(object):
    def setupUi(self, entrance_form):
        entrance_form.setObjectName("entrance_form")
        entrance_form.resize(403, 338)
        entrance_form.setSizeGripEnabled(False)
        entrance_form.setModal(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(entrance_form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(entrance_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.label = QtWidgets.QLabel(self.login_page)
        self.label.setGeometry(QtCore.QRect(70, 20, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.login_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 110, 271, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.login_input.setFont(font)
        self.login_input.setText("")
        self.login_input.setObjectName("login_input")
        self.verticalLayout.addWidget(self.login_input)
        self.password_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_input.setFont(font)
        self.password_input.setText("")
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.entrance_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entrance_button.setFont(font)
        self.entrance_button.setObjectName("entrance_button")
        self.verticalLayout.addWidget(self.entrance_button)
        self.button_registration = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_registration.setFont(font)
        self.button_registration.setObjectName("button_registration")
        self.verticalLayout.addWidget(self.button_registration)
        self.stackedWidget.addWidget(self.login_page)
        self.menu_page = QtWidgets.QWidget()
        self.menu_page.setObjectName("menu_page")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.menu_page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 30, 271, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_add_task = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_task.sizePolicy().hasHeightForWidth())
        self.button_add_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_task.setFont(font)
        self.button_add_task.setObjectName("button_add_task")
        self.verticalLayout_2.addWidget(self.button_add_task)
        self.button_edit_task = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit_task.sizePolicy().hasHeightForWidth())
        self.button_edit_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_edit_task.setFont(font)
        self.button_edit_task.setObjectName("button_edit_task")
        self.verticalLayout_2.addWidget(self.button_edit_task)
        self.button_check_task = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_check_task.sizePolicy().hasHeightForWidth())
        self.button_check_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_check_task.setFont(font)
        self.button_check_task.setObjectName("button_check_task")
        self.verticalLayout_2.addWidget(self.button_check_task)
        self.button_new_teacher = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_new_teacher.sizePolicy().hasHeightForWidth())
        self.button_new_teacher.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_new_teacher.setFont(font)
        self.button_new_teacher.setObjectName("button_new_teacher")
        self.verticalLayout_2.addWidget(self.button_new_teacher)
        self.stackedWidget.addWidget(self.menu_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.registration_personal_name_input = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registration_personal_name_input.sizePolicy().hasHeightForWidth())
        self.registration_personal_name_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registration_personal_name_input.setFont(font)
        self.registration_personal_name_input.setObjectName("registration_personal_name_input")
        self.verticalLayout_4.addWidget(self.registration_personal_name_input)
        self.regidtration_login_input = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regidtration_login_input.sizePolicy().hasHeightForWidth())
        self.regidtration_login_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.regidtration_login_input.setFont(font)
        self.regidtration_login_input.setObjectName("regidtration_login_input")
        self.verticalLayout_4.addWidget(self.regidtration_login_input)
        self.regitration_password_1 = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regitration_password_1.sizePolicy().hasHeightForWidth())
        self.regitration_password_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.regitration_password_1.setFont(font)
        self.regitration_password_1.setObjectName("regitration_password_1")
        self.verticalLayout_4.addWidget(self.regitration_password_1)
        self.registration_password_2 = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registration_password_2.sizePolicy().hasHeightForWidth())
        self.registration_password_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registration_password_2.setFont(font)
        self.registration_password_2.setObjectName("registration_password_2")
        self.verticalLayout_4.addWidget(self.registration_password_2)
        self.registration_button_register = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registration_button_register.sizePolicy().hasHeightForWidth())
        self.registration_button_register.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registration_button_register.setFont(font)
        self.registration_button_register.setObjectName("registration_button_register")
        self.verticalLayout_4.addWidget(self.registration_button_register)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_3.addWidget(self.stackedWidget)

        self.retranslateUi(entrance_form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(entrance_form)
        entrance_form.setTabOrder(self.login_input, self.password_input)
        entrance_form.setTabOrder(self.password_input, self.entrance_button)
        entrance_form.setTabOrder(self.entrance_button, self.button_registration)

    def retranslateUi(self, entrance_form):
        _translate = QtCore.QCoreApplication.translate
        entrance_form.setWindowTitle(_translate("entrance_form", "Вход"))
        self.label.setText(_translate("entrance_form", "Преподаватель"))
        self.login_input.setPlaceholderText(_translate("entrance_form", "Логин"))
        self.password_input.setPlaceholderText(_translate("entrance_form", "Пароль"))
        self.entrance_button.setText(_translate("entrance_form", "Вход"))
        self.button_registration.setText(_translate("entrance_form", "Регистрация (студент)"))
        self.button_add_task.setText(_translate("entrance_form", "Добавить задание"))
        self.button_edit_task.setText(_translate("entrance_form", "Редактировать задание"))
        self.button_check_task.setText(_translate("entrance_form", "Проверить задание"))
        self.button_new_teacher.setText(_translate("entrance_form", "Регистрация преподавателя"))
        self.registration_personal_name_input.setPlaceholderText(_translate("entrance_form", "ФИО"))
        self.regidtration_login_input.setPlaceholderText(_translate("entrance_form", "Логин"))
        self.regitration_password_1.setPlaceholderText(_translate("entrance_form", "Пароль"))
        self.registration_password_2.setPlaceholderText(_translate("entrance_form", "Повторите пароль"))
        self.registration_button_register.setText(_translate("entrance_form", "Регистрация"))
