# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_add_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(865, 659)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.figure_info = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figure_info.sizePolicy().hasHeightForWidth())
        self.figure_info.setSizePolicy(sizePolicy)
        self.figure_info.setMaximumSize(QtCore.QSize(16777215, 150))
        self.figure_info.setObjectName("figure_info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.figure_info)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.figure_info_key_words = QtWidgets.QTextBrowser(self.figure_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.figure_info_key_words.setFont(font)
        self.figure_info_key_words.setAcceptRichText(False)
        self.figure_info_key_words.setObjectName("figure_info_key_words")
        self.horizontalLayout.addWidget(self.figure_info_key_words)
        self.figure_info_type = QtWidgets.QLabel(self.figure_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figure_info_type.sizePolicy().hasHeightForWidth())
        self.figure_info_type.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.figure_info_type.setFont(font)
        self.figure_info_type.setAlignment(QtCore.Qt.AlignCenter)
        self.figure_info_type.setObjectName("figure_info_type")
        self.horizontalLayout.addWidget(self.figure_info_type)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.figure_info_possible_words = QtWidgets.QTextBrowser(self.figure_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.figure_info_possible_words.setFont(font)
        self.figure_info_possible_words.setAcceptRichText(False)
        self.figure_info_possible_words.setObjectName("figure_info_possible_words")
        self.verticalLayout_2.addWidget(self.figure_info_possible_words)
        self.gridLayout_2.addWidget(self.figure_info, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_add_figure = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_figure.sizePolicy().hasHeightForWidth())
        self.button_add_figure.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_figure.setFont(font)
        self.button_add_figure.setObjectName("button_add_figure")
        self.verticalLayout_3.addWidget(self.button_add_figure)
        self.button_add_task = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_task.sizePolicy().hasHeightForWidth())
        self.button_add_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_task.setFont(font)
        self.button_add_task.setObjectName("button_add_task")
        self.verticalLayout_3.addWidget(self.button_add_task)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_accept_text = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_accept_text.sizePolicy().hasHeightForWidth())
        self.button_accept_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.button_accept_text.setFont(font)
        self.button_accept_text.setObjectName("button_accept_text")
        self.verticalLayout.addWidget(self.button_accept_text)
        self.figures_buttons_list = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.figures_buttons_list.setFont(font)
        self.figures_buttons_list.setObjectName("figures_buttons_list")
        self.verticalLayout.addWidget(self.figures_buttons_list)
        self.figures_counter_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figures_counter_label.sizePolicy().hasHeightForWidth())
        self.figures_counter_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.figures_counter_label.setFont(font)
        self.figures_counter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.figures_counter_label.setObjectName("figures_counter_label")
        self.verticalLayout.addWidget(self.figures_counter_label)
        self.button_add_key_words = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_key_words.sizePolicy().hasHeightForWidth())
        self.button_add_key_words.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_key_words.setFont(font)
        self.button_add_key_words.setObjectName("button_add_key_words")
        self.verticalLayout.addWidget(self.button_add_key_words)
        self.button_add_possible_words = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_possible_words.sizePolicy().hasHeightForWidth())
        self.button_add_possible_words.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_possible_words.setFont(font)
        self.button_add_possible_words.setObjectName("button_add_possible_words")
        self.verticalLayout.addWidget(self.button_add_possible_words)
        self.task_name_input = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_name_input.sizePolicy().hasHeightForWidth())
        self.task_name_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task_name_input.setFont(font)
        self.task_name_input.setObjectName("task_name_input")
        self.verticalLayout.addWidget(self.task_name_input)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.task_text = QtWidgets.QTextEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task_text.setFont(font)
        self.task_text.setObjectName("task_text")
        self.gridLayout_2.addWidget(self.task_text, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setRowStretch(0, 10)
        self.gridLayout_2.setRowStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.figure_info.setTitle(_translate("Dialog", "Информация о добавляемом обороте"))
        self.figure_info_key_words.setPlaceholderText(_translate("Dialog", "Ключевые слова"))
        self.figure_info_type.setText(_translate("Dialog", "Тип оборота"))
        self.figure_info_possible_words.setPlaceholderText(_translate("Dialog", "Диапазон выделения"))
        self.button_add_figure.setText(_translate("Dialog", "Добавить оборот"))
        self.button_add_task.setText(_translate("Dialog", "Завершить\n"
"составление задания"))
        self.button_accept_text.setText(_translate("Dialog", "Принять текст"))
        self.figures_counter_label.setText(_translate("Dialog", "Оборотов добавлено:\n"
"0"))
        self.button_add_key_words.setText(_translate("Dialog", "Добавить\n"
"ключевые слова"))
        self.button_add_possible_words.setText(_translate("Dialog", "Добавить\n"
"диапазон выделения"))
        self.task_name_input.setPlaceholderText(_translate("Dialog", "Название задания"))
        self.task_text.setPlaceholderText(_translate("Dialog", "Введите текст задания"))
